apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: canaryguard
  namespace: canaryguard

  labels:
    release: kube-prometheus-stack

spec:

  selector:
    matchLabels:
      app: canaryguard

  namespaceSelector:
    matchNames:
      - canaryguard

  endpoints:

    - port: http

      path: /metrics

      interval: 15s